services:
  nginx:
    build: ./nginx
    container_name: monitored-nginx
    ports:
      - "8080:80"

  redis:
    image: redis:alpine
    container_name: monitoring-redis

  watcher:
    build: ./watcher
    container_name: nginx-watcher
    depends_on:
      - nginx
      - redis
